/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bucketupdater_CONSTANTS_H
#define bucketupdater_CONSTANTS_H

#include "bucketupdater_types.h"

namespace scribe {
    namespace thrift {

        class bucketupdaterConstants {
        public:
            bucketupdaterConstants();

        };

        extern const bucketupdaterConstants g_bucketupdater_constants;

    }
} // namespace

#endif
