/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bucketupdater_constants.h"

namespace scribe {
    namespace thrift {

        const bucketupdaterConstants g_bucketupdater_constants;

        bucketupdaterConstants::bucketupdaterConstants() {
        }

    }
} // namespace

